### ISSUE TITLE
Cant input the number 4 into the hex code input

### ISSUE THREAD

**Issue by stamnostomp** [raysan5/rguistyler#4]
when inputting a hex code when I hit the number 4 it will gray out the app and the app will be unresponsive untell I input a number less than 4 ![Alt text](https://i.imgur.com/VTDASFZ.png)

so the only way I have found to get the number 4 in my hex code is by using the colour selector to get a number with 4 and deleting around it

**Comment by raysan5** [comment]
Oh! Good catch! Editor conflicts with some shortcuts. I will review it asap.

**Comment by raysan5** [comment]
Fixed, it should be ok on next release
